"""Keep the CPU, CUDA and development dependency locks unambiguous."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

from scripts.check_deps import unexpected_problems

ROOT = Path(__file__).resolve().parents[1]
_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==(\S+)")


def _lock(name: str) -> dict[str, str]:
    """Pinned versions of a lock generated by scripts/lock_deps.sh."""
    pins = {}
    lines = (ROOT / name).read_text().splitlines()
    for index, line in enumerate(lines):
        match = _PIN.match(line)
        if not match:
            continue
        # Every pin carries its hashes on the following continuation lines.
        assert line.endswith("\\"), f"{name}: {line} has no hashes"
        assert "--hash=sha256:" in lines[index + 1], f"{name}: {line} has no hashes"
        pins[canonicalize_name(match.group(1))] = match.group(2)
    assert pins, f"{name} pins nothing"
    return pins


def _inputs(name: str, seen: set[str] | None = None) -> set[str]:
    """Direct dependency names declared by a requirements*.in file and its includes."""
    seen = seen if seen is not None else set()
    if name in seen:
        return set()
    seen.add(name)
    names = set()
    for raw_line in (ROOT / name).read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-r "):
            names |= _inputs(line[3:].strip(), seen)
            continue
        names.add(canonicalize_name(Requirement(line).name))
    return names


def test_locks_cover_every_direct_dependency() -> None:
    for lock, source in (
        ("requirements.txt", "requirements-cpu.in"),
        ("requirements-cuda.txt", "requirements-cuda.in"),
        ("requirements-dev.txt", "requirements-dev.in"),
    ):
        missing = _inputs(source) - _lock(lock).keys()
        assert not missing, f"{lock} lacks {sorted(missing)} from {source}"


def test_cpu_lock_selects_cpu_wheels_only() -> None:
    cpu = _lock("requirements.txt")
    assert cpu["torch"].endswith("+cpu")
    assert cpu["torchvision"].endswith("+cpu")
    assert "onnxruntime" in cpu
    assert "onnxruntime-gpu" not in cpu
    assert "https://download.pytorch.org/whl/cpu" in (ROOT / "requirements.txt").read_text()


def test_cuda_lock_selects_cuda_wheels_only() -> None:
    cuda = _lock("requirements-cuda.txt")
    assert cuda["torch"].endswith("+cu130")
    assert cuda["torchvision"].endswith("+cu130")
    assert "onnxruntime-gpu" in cuda
    # insightface declares onnxruntime; it installs the same module as
    # onnxruntime-gpu and would silently drop the CUDA provider.
    assert "onnxruntime" not in cuda
    assert "https://download.pytorch.org/whl/cu130" in (
        ROOT / "requirements-cuda.txt"
    ).read_text()


def test_no_lock_installs_opencv_with_gui_next_to_headless() -> None:
    for lock in ("requirements.txt", "requirements-cuda.txt", "requirements-dev.txt"):
        pins = _lock(lock)
        assert "opencv-python-headless" in pins
        assert "opencv-python" not in pins, lock


def test_cpu_and_cuda_share_the_application_stack() -> None:
    cpu = _lock("requirements.txt")
    cuda = _lock("requirements-cuda.txt")
    for name in _inputs("requirements.in"):
        assert cpu[name] == cuda[name], f"{name}: CPU {cpu[name]} vs CUDA {cuda[name]}"
    assert cpu["torch"].split("+")[0] == cuda["torch"].split("+")[0]


def test_development_lock_is_the_cpu_lock_plus_tools() -> None:
    cpu = _lock("requirements.txt")
    dev = _lock("requirements-dev.txt")
    assert {name: dev.get(name) for name in cpu} == cpu
    assert {"pytest", "httpx", "ruff", "pip-audit", "uv"} <= dev.keys()


def test_locks_are_installed_without_resolving() -> None:
    dockerfile = (ROOT / "Dockerfile").read_text()
    assert "pip install --no-cache-dir --no-deps --require-hashes" in dockerfile
    assert "cpu) lock=requirements.txt" in dockerfile
    assert "cuda) lock=requirements-cuda.txt" in dockerfile
    assert "check_deps.py" in dockerfile
    assert not (ROOT / "Dockerfile.gpu").exists()
    ci = (ROOT / ".github" / "workflows" / "ci.yml").read_text()
    assert "pip install --no-deps --require-hashes -r requirements-dev.txt" in ci
    assert "scripts/check_deps.py" in ci
    assert "git diff --exit-code" in ci
    install = (ROOT / "scripts" / "install.sh").read_text()
    assert "pip install --no-deps --require-hashes -r requirements.txt" in install


def test_gpu_compose_only_overrides_the_cpu_service() -> None:
    compose = (ROOT / "docker-compose.yml").read_text()
    gpu = (ROOT / "docker-compose.gpu.yml").read_text()
    assert "IRIS_PROFILE: cpu" in compose
    assert "IRIS_PROFILE: cuda" in gpu
    assert "-cuda" in gpu
    assert "environment:" not in gpu
    assert "driver: nvidia" in gpu


def test_package_metadata_does_not_duplicate_profile_dependencies() -> None:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    assert "dependencies" not in project
    assert "optional-dependencies" not in project
    assert project["requires-python"] == ">=3.13,<3.14"


def test_dependency_check_tolerates_only_deliberate_exclusions() -> None:
    assert unexpected_problems("insightface 2.0 requires opencv-python, which is not installed.") == []
    assert unexpected_problems("insightface 2.0 requires onnxruntime, which is not installed.") == []
    assert unexpected_problems("No broken requirements found.") == []
    broken = "timm 1.0.30 requires torch, which is not installed."
    assert unexpected_problems(broken) == [broken]
    conflict = "fastapi 0.142.2 has requirement starlette<2, but you have starlette 2.0."
    assert unexpected_problems(conflict) == [conflict]


def test_vision_extension_loads_with_installed_torch() -> None:
    import torch
    import torchvision

    cpu = _lock("requirements.txt")
    assert torch.__version__ == cpu["torch"]
    assert torch.version.cuda is None
    assert torchvision.__version__ == cpu["torchvision"]
    assert hasattr(torch.ops.torchvision, "nms")
